### ISSUE TITLE
I tried this from a mobile phone.   Should this demo work from a mobile device like a Nexus 5?

### ISSUE THREAD

**Issue by bkbonner** [rtc-io/demo-quickconnect#1]
tried this from my nexus 5.

At first it just showed No Data received.

I checked the Request Desktop Site option and then it prompted me for Mic and Audio....but it just took a snapshot of me and showed no video.

The connection info in the server log looked the same.

 rtc-switchboard writing data to spark scope:  +16ms /announce|{"id":"09da1e99-e016-4f55-9e5d-30e887375c8c"}|{"browser":"chrome","browserVersion":31,"id":"09da1e99-e016-4f55-9e5d-30e887375c8c","agent":"signaller@0.16.0","room":"main"}

**Comment by DamonOehlman** [comment]
We've done no mobile optimizations for this demo, but I think it's a good idea so happy to do that sometime soon.

I believe it should work from chrome for Android, but I do recall @silviapfeiffer mentioning there were some issues last time she tried it.

**Comment by silviapfeiffer** [comment]
I wasn't able to get apprtc working on the nexus 5 do I think there are issues beyond our control for this platform still. Apprtc  works on the nexus 7 though.

**Comment by bkbonner** [comment]
Thank you.  This sounds like a great project

Brian

**Comment by silviapfeiffer** [comment]
BTW: should be working now. Worth another test.

**Comment by bkbonner** [comment]
I tried it on a Nexus 5.   It doesn't update the screen on the nexus 5 w/ photo from desktop (mac air).

The mac air is a bit distorted (aspect ratio appears off), but it live updates.
![screen shot 2014-03-18 at 8 43 48 am](https://f.cloud.github.com/assets/667769/2447667/3f24d01a-ae9b-11e3-9395-8dba3a399a43.png)

On the phone - this image doesn't update at all.
![screenshot_2014-03-18-08-42-25](https://f.cloud.github.com/assets/667769/2447692/9d44e8f6-ae9b-11e3-94be-8ae518cc7e87.png)

**Comment by bkbonner** [comment]
Not my most flattering shots ;)

**Comment by silviapfeiffer** [comment]
Did you update your modules before you ran it? There have been some recent changes that fixed that.
run "npm update" to update the modules.

**Comment by DamonOehlman** [comment]
@bkbonner Just wondering if this is now working for you on your Nexus 5?
