### ISSUE TITLE
broadcast event issue

### ISSUE THREAD

**Issue by santhoshreddyk** [rtc-io/demo-quickconnect#4]
Hi,

I have mixed up rtc-screenshare with quickconnect module. and did the following code.
when i call shareVideo() method (one clicking some button on UI) i am capturing the screen and broadcasting. But the problem is, it is not firing the stream:added event on the other side.

can you please give me any clue??

var qConnect = quickconnect(location.href + '../../', {room: room, iceServers: iceServers});
  qConnect.createDataChannel('chat');
  qConnect.on('stream:added', renderRemote);
  qConnect.on('stream:removed', removeRemote);
  qConnect.on('channel:opened:chat', function(id, dc) {
    qsa('.chat').forEach(tweak('+open'));
    dc.onmessage = function(evt) {
      if (messages) {
        messages.appendChild(crel('li', evt.data));
      }
    };
    channel = dc;
    console.log('dc open for peer: ' + id);
  });
function shareVideo() {
    screenshare.window(function(err, constraints) {
    localMedia = media(constraints);
    localMedia.render(local);
    localMedia.on('capture', function(stream) {
      console.log("on capture method");
      qConnect.broadcast(stream);
      //qConnect.addStream(stream);
    });
  });
}

**Comment by santhoshreddyk** [comment]
Used quickconnnect in reactive mode.. issue is fixed..

**Comment by DamonOehlman** [comment]
Awesome - nice work @santhoshreddyk - sorry I didn't get back to you with a reply, I hadn't managed to get time to investigate yet...  really appreciate your efforts.
