### ISSUE TITLE
Cannot see with each other using the same id

### ISSUE THREAD

**Issue by betimer** [rtc-io/demo-quickconnect#7]
![2016-07-15 12_44_22-program manager](https://cloud.githubusercontent.com/assets/8111748/16862057/f92a57a0-4a89-11e6-844d-f62b1726a9b9.png)

Open 2 tabs, cannot see each other.
The picture is the screen of chrome browser console.

**Comment by silviapfeiffer** [comment]
I think the switchboard server is currently down. Since this is a testing
service only, how urgently do you need this?

Best Regards,
Silvia.

**Comment by betimer** [comment]
Thank you for your response.
No, I just see some demo, not use this project yet. But would like to let you know the issue.

Cheers
Xin

**Comment by magestican** [comment]
@silviapfeiffer  Would it be possible for you to bring this back online? Its really useful to test different connection settings related to TURN and STUN, so that we can find if we are doing something wrong or if there is a problem in quickconnect

**Comment by silviapfeiffer** [comment]
https://switchboard.rtc.io/ is back online - sorry about the delays
